postgres:
  image: postgres:10.1-alpine
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'admin'
    POSTGRES_DB: 'instadev'
  volumes:
    - ./init:/docker-entrypoint-initdb.d/

  
